### ISSUE TITLE
Milestone3 To-do List

### ISSUE THREAD

**Issue by nichowu** [UBC-MDS/DSCI_532_Group18_Allstars-R#1]
Next meeting: Thursday 9:00pm. 

- [x] Copy over your contributing guidelines, code of conduct README file, and the necessary data files, repo structure. (Nicholas)

if any feedback given:
- [x] also include a link to the issue where you write your feedback

- [x] implement most of your milestone 2 dashboard 
- Deepak will do card arrange layout.
- William will do world map plot-geo
- Zeliha will the the other three bar chart (keep in mind we might want to try link the world map with a bar chart). 

things to change from M1:
- [x] Add padding for instruction text  (Nicholas)
- [x] Fix color of the bar chart to turquoise(Nicholas)
- [x] Worldmap: Link Worldmap to another plot(?) (keep this in mind for M3, possible item for M4).  (Zeliha). 
- [x] Remove the legend & change the color scheme to "diverging". 

- [x] rearrange the dropdown menu ( to be on top) **(Deepak)**

- [x] reflection-milestone3.md (live under doc folder) **(Nicholas)**
- [x] give peer feedback to another group (optional) (Everyone leaves a feedback in issue #2 )
- [x] deployment!!! **( Deepak)**
- [x] README with a link to the deployed R dashboard and a new image/gif **(William)**
- [x]  create a release
- [x] canvas-submission.html

**Comment by zmerpez** [comment]
Nice work team!

**Comment by williamxu7** [comment]
Awesome job!
